### ISSUE TITLE
Files Old Vulkan!

### ISSUE THREAD

**Issue by madrina4** [KhronosGroup/Vulkan-Tools#1023]
Could you provide these old files for download? they are no longer on the website.

VulkanSDK-1.1.130.0-Installer.exe
VulkanSDK-1.0.68.0-Installer.exe

vulkansdk-linux-x86_64-1.1.130.0.tar.gz
vulkansdk-linux-x86_64-1.0.68.0.run

VulkanRT-1.1.130.0-Installer.exe
VulkanRT-1.0.68.0-Installer.exe

VulkanRT-1.1.130.0-Components.zip
VulkanRT-1.0.68.0-Components.zip

**Comment by charles-lunarg** [comment]
The current SDK and runtime is backwards compatible with Vulkan 1.0 drivers. There isn't a need to use an exact SDK version from 2017 and 2019.  Generally, old runtimes and SDK's are removed from the website so as to not confuse users and clutter the website, since the components in the latest SDK completely supersede the listed SDK's. This is also not the right place to ask questions about the SDK itself, that would be [https://vulkan.lunarg.com/issue](https://vulkan.lunarg.com/issue), so I am going ahead and closing this issue. Feel free to open up an issue on vulkan.lunarg.com for further discussion.
