### ISSUE TITLE
Directly opening DEMOS.sln in 'C:\VulkanSDK\1.3.290.0\Demos' has some issues with the include hierarchy.

### ISSUE THREAD

**Issue by yankun2024** [KhronosGroup/Vulkan-Tools#1028]
The
https://github.com/KhronosGroup/Vulkan-Tools/blob/4c63e845962ff3b197855f3ae4907a47d0863f5a/cube/cube.c#L56
Should be 
`#include "Volk/volk.h"`

And
https://github.com/KhronosGroup/Vulkan-Tools/blob/4c63e845962ff3b197855f3ae4907a47d0863f5a/cube/cube.cpp#L50
Also

**Comment by charles-lunarg** [comment]
This is ultimately an SDK packaging issue, and has already gotten an open issue:

https://vulkan.lunarg.com/issue/home?limit=10;q=;mine=false;org=false;khronos=false;lunarg=false;indie=false;status=new,open

While I *could* modify vkcube.c/vkcube.cpp to include volk in the 'right' place for the Windows SDK, I'd have to work around that for the local build (eg, this repo on its own). That is very un-fun and brittle. I would much rather the SDK be consistent across platforms so that this repo can use that single location. 

Because this is a packaging issue (plus, demo's come the SDK), I am going to close the issue.
