### ISSUE TITLE
vulkaninfo: VkSharedPresentSurfaceCapabilitiesKHR requested from devices not supporting VK_KHR_shared_presentable_image

### ISSUE THREAD

**Issue by cubanismo** [KhronosGroup/Vulkan-Tools#258]
vulkaninfo is requesting shared presentable surface capabilities from physical devices that don't report support for the associated device extension VK_KHR_shared_presentable_image.  Our driver doesn't support this extension, and hence doesn't populate the extension struct, meaning the data returned to vulkaninfo will basically be uninitialized.  In general, I believe vulkaninfo needs to check for device extension support before passing in associated physical device capability or property query structs in pNext to a given device.

**Comment by charles-lunarg** [comment]
If vulkaninfo is outputting anything for VK_KHR_shared_presentable_image when the device doesn't support it, then it is a bug. Otherwise it shouldn't be an issue for an application to submit a pNext chain containing structures which are apart of extensions the device doesn't support. 

Vulkan Spec 2.7.2, "Implicit Valid Usage", the "Valid Usage for Structure Types" section states:
> Any component of the implementation (the loader, any enabled layers, and drivers) must skip over, without processing (other than reading the sType and pNext members) any structures in the chain with sType values not defined by extensions supported by that component.

**Comment by charles-lunarg** [comment]
Further info:
While Vulkaninfo does submit structs in pNext chains for every extension it supports output of, the driver should accurately report which extensions are supported, and vulkainfo will use this to only output information about structs the driver supports. Otherwise, when iterating the pNext chain for output, it will ignore such structs.
