### ISSUE TITLE
vulkaninfo : many warnings when building demos

### ISSUE THREAD

**Issue by mikew-lunarg** [KhronosGroup/Vulkan-Tools#317]
Windows 10, VS2015.  
Building DEMOS.sln, get many (hundreds?) of messages of the form:
```
1>c:\vulkansdk\1.1.130.0\demos\vulkaninfo.hpp(904): warning C4800: 'VkBool32': forcing value to bool 'true' or 'false' (performance warning)
```

**Comment by charles-lunarg** [comment]
It seems that this warning is not emitted in vs2017 and not by default in 2019. 
Msvc's suggested fix is to compare the int to 1 ie `(value == 1)`. However, since this warning was made optional, I would prefer to disable the warning in the build options.
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4800?view=vs-2019

**Comment by mikew-lunarg** [comment]
It's certainly not performance-sensitive code, this is just to clear up the build specifically called out in the Getting Started guide, and thus quite visible.  It doesn't happen on other platforms?

**Comment by charles-lunarg** [comment]
I've tested on vs 2017 and vs 2019 and can confirm it doesn't emit the error. I've also not seen it on any other platforms i've tested on (ubuntu 19 & gcc9 specifically)
Since I added the `static_cast<bool>(...)` in #301, there isn't any implicit conversion.

**Comment by mikew-lunarg** [comment]
Ok.  The main concern was not fixing in the build system if it should be fixed in the code, as determined by other systems showing the same warning (including linux/mac)  Generally it is better to fix in the code when possible.

**Comment by mikew-lunarg** [comment]
PR #301 is merged, closing
