### ISSUE TITLE
MakeFile Missing

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/Vulkan-Tools#394]
Hello,

What I happening when I want to fully buid and install your GitHub :

![FalseCMakesErrorButMakeFileKeepMissing](https://user-images.githubusercontent.com/30596513/81474282-983ed300-9204-11ea-9526-e2dcf3fd18c1.jpg)

Thank you in advance to bring the makefile for fully install the GitHub,

Regards.

Azaretdodo.

**Comment by jeremyk-lunarg** [comment]
My best guess to what is causing your problem is a malformed CMake invocation.

Please see our [BUILD.md](https://github.com/KhronosGroup/Vulkan-Tools/blob/master/BUILD.md) for step-by-step instruction on building the repo.

If you would like to better understand how the CMake command works, please see the documentation for the `cmake` command [here](https://cmake.org/cmake/help/v3.10/manual/cmake.1.html).
Make sure it is for CMake 3.10.2, as that is the version of CMake all of our repos are designed to use.

**Comment by Azaretdodo** [comment]
I am under cmake 3.17 maybe too much stronger?

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by jeremyk-lunarg** [comment]
Given the error you are getting, I would guess it has been caused by some mistake while setting up the repo on your system.

I would highly recommend the following steps:

1. Delete the repo clone from your system.
1. Reclone the repo.
1. Closely follow the steps-by-step instructions in [BUILD.md](https://github.com/KhronosGroup/Vulkan-Tools/blob/master/BUILD.md#repository-set-up).

**Comment by Azaretdodo** [comment]
I am Following the BUILD.md file I have happenning this errors : 

![error1happenning](https://user-images.githubusercontent.com/30596513/81582126-efcd7200-93af-11ea-82b2-999e8a69a6af.jpg)
![error2happenning](https://user-images.githubusercontent.com/30596513/81582150-f825ad00-93af-11ea-9e59-aef374a31f4c.jpg)

**Comment by Azaretdodo** [comment]
I will tried to repair the errors happening
