### ISSUE TITLE
no makefile created after the good command line adviced in the build.md

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/Vulkan-Tools#400]
Hello,

After running this command line no makefile created :

![NoMakeFileCreatedAfterRunningThisAdviceCommandLine](https://user-images.githubusercontent.com/30596513/81718824-823b4780-947c-11ea-8651-463160ff98ce.jpg)

Thank you in advance to help myself created a makefile for fully install your GitHub,

Regards.

Azaretdodo.

**Comment by jeremyk-lunarg** [comment]
When building this repo on Linux, the CMake command also requires a path to the Vulkan-Loader install directory via `-DVULKAN_LOADER_INSTALL_DIR=<path to Vulkan-Loader install dir>`.

It seems your path to the Vulkan-Headers install directory is incorrect as well.

The Vulkan-Headers install directory should be in `Vulkan-Headers/build/install`.

If you used the `update_deps.py` script, Vulkan-Headers and Vulkan-Loader should be in whatever directory you pointed the `update_deps.py` script too.

Example:
If you ran `python update_deps.py --dir=../external` in the `build` dir, then Vulkan-Headers and Vulkan-Loader should be in the `Vulkan-Tools/external` directory.

**Comment by Azaretdodo** [comment]
Too with external directory no makefile created

Thank you in advance to bring a makefile,

Regards.


Azaretdodo.

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by jeremyk-lunarg** [comment]
Mr. Azaretdodo, we have been more than patient with you, but it seems that all of your problems can be solved the same way, by reading the BUILD.md documentation carefully and following its steps precisely.

Because of this, I request you refrain from creating any new issues on the matter and refer back to the advice given to you in issues #394 and #398.

Any further issues on this matter will be closed as duplicates and may be marked against you as spam.
