### ISSUE TITLE
A lot of error when I try to build

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/Vulkan-Tools#432]

**Comment by Azaretdodo** [comment]
Hello sorry the copy past failed :(

**Comment by eloj** [comment]
Please end this experiment. You're being abusive by opening all these "issues" in [different projects](https://github.com/doxygen/doxygen/issues/7767), and then wasting everybodys time by pasting screenshots of your terminal error messages, errors which are always generated because you refuse to follow basic instructions.

You already have nine(!!) closed issues in this repository alone.

Please stop.
