### ISSUE TITLE
vulkaninfo: Heap corruption in freepNextChain

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-Tools#580]
Running vulkaninfo on my Windows 11 laptop, Geforce RTX 3060 (462.21)and Intel graphics results in HEAP CORRUPTION in the second call to  freepNextChain(static_cast<VkStructureHeader *>(features2.pNext));  Bisected to 1.2.190 header update.  It happens freeing a VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INTEGER_DOT_PRODUCT_FEATURES_KHR.

**Comment by Tony-LunarG** [comment]
[rubyvinfo.txt](https://github.com/KhronosGroup/Vulkan-Tools/files/7500412/rubyvinfo.txt
[loader-debug.txt](https://github.com/KhronosGroup/Vulkan-Tools/files/7500427/loader-debug.txt)
)

**Comment by charles-lunarg** [comment]
This appears to not be due to vulkaninfo but from a driver using a different definition of the `VkPhysicalDeviceShaderIntegerDotProductFeaturesKHR` than one found in the spec, as evidenced by manually increasing the 'size' of the structure by 8 bytes, which is enough to prevent the WinCRT from detecting a write out of bounds.

I'm not going to close the issue but am very skeptical of any other source for the bug. Its just too specific of a fix for many other solutions to make sense.

**Comment by ziga-lunarg** [comment]
Ran into the same issue during SDK testing. Running `vulkaninfo --summary` gives:

>         apiVersion         = 4202673 (1.2.177)
        driverVersion      = 1648064 (0x1925c0)
        vendorID           = 0x8086
        deviceID           = 0x9bc4
        deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
        deviceName         = Intel(R) UHD Graphics
        driverID           = DRIVER_ID_INTEL_PROPRIETARY_WINDOWS
        driverName         = Intel Corporation
        driverInfo         = Intel driver
        conformanceVersion = 1.2.3.2
