### ISSUE TITLE
[Question] How to solve "failed to establish dbus connection" and stuttering vkcube

### ISSUE THREAD

**Issue by blakat360** [KhronosGroup/Vulkan-Tools#605]
I'm on nixOS linux. My CPU is AMD Ryzen 9 5950x 16 core. My GPU is a Nvidia 3080 ti.

When running vulkaninfo and vkcube I get the following warning: ```failed to establish dbus connection```.

The full output of vulkaninfo can be viewed here: https://pastebin.com/98CKsuGq.

I initially started down the rabbit hole as I saw a weird rhythmic stuttering in both youtube and gstreamer streamed video. This same stuttering is present when I run vkcube.

I'm pretty sure this is a software issue as when I boot into windows, I don't have this issue.

**Comment by charles-lunarg** [comment]
This doesn't appear to be an issue related to vulkaninfo but rather is due to the way your system is set up. Since its occuring in other applications, I suspect driver issues.

Because this repo is for Vulkan related tooling, I am closing the issue as this is not the right forum for this. Consider making issues in the graphics drivers forums, such as https://forums.developer.nvidia.com
