### ISSUE TITLE
vulkaninfo -j quietly changed behavior in an incompatible way

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-Tools#646]
`vulkaninfo -j` used to send JSON information to `stdout`.

Now it creates a file with a difficult-to-predict name, like `VP_VULKANINFO_NVIDIA_GeForce_RTX_2080_Ti_472_368_0.json` (ironically, you can only figure out what the name will be after you get the `vulkaninfo` results).

There is now a `-o filename` switch to redirect the output... but that switch causes an error when run on older `vulkaninfo` executables and so is not useful if you need to support legacy SDKs.

This breaks our CI in numerous places - also ironically, not in **Vulkan-Tools** CI, which doesn't have an explicit test for this behavior (and should).

I'm curious why a clear break in compatibility was allowed.  A new switch like `-J` with new behavior could easily have been defined, that didn't break older behavior.

**Comment by lunarpapillo** [comment]
The actual data in the fields has also changed.  The older `vulkaninfo` included:
```
        "deviceType": 2,
```
while the newer one instead returns:
```
        "deviceType": "VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU",
```
I'm not sure what other data types have changed.

**Comment by charles-lunarg** [comment]
This was by design. DevSim is being deprecated and replaced with the Vulkan-Profiles output. It follows a different schema, and is much more 'user' friendly. 
While it would be possible to keep the existing output by adding a new switch, there is little sense in keeping DevSim around if it is to eventually be removed at an unknown later date. There would be pain for anyone expecting the old output.

Vulkaninfo doesn't make any guarantees of a perfectly stable output. It does make guarantees that the json files are well formed and following their respective schema. Issue is, we changed the schemas.
