### ISSUE TITLE
vulkaninfo: error undeclared identifier VK_VIDEO_CODEC_OPERATION_DECODE_H264_BIT_KHR 

### ISSUE THREAD

**Issue by BlingRob** [KhronosGroup/Vulkan-Tools#728]
Good day!
I'm building the Vulkan SDK from source and using only CMake (without python and parsing vk.xml). Because of this, there's no `VK_ENABLE_BETA_EXTENSIONS` and I get an error in _vulkaninfo.hpp_ on lines 1222 and 1223, because `VK_VIDEO_CODEC_OPERATION_DECODE_H264_BIT_KHR` and `VK_VIDEO_CODEC_OPERATION_DECODE_H265_BIT_KHR` aren't defined. sdk-1.3.236 doesn't have this problem. I wanted to ask: now, I have to use python to obtain `VK_ENABLE_BETA_EXTENSIONS` or is there another way to make it, but I'm doing something wrong?

**Comment by charles-lunarg** [comment]
Did you make sure to run `update_deps.py` and reset your CMake cache before the run?
I updated my local build, found I got the same errors, then reset my CMake cache and it compiled cleanly.

**Comment by BlingRob** [comment]
I know this solves the problem, but I want to avoid using python. Other SDK components allow this. So I need to figure out a way around `update_deps.py `. Ok.
Thank you for answer.

**Comment by charles-lunarg** [comment]
What it sounds like was happening was that tip of tree Vulkan-Tools was trying to be built with the Vulkan-Headers from the SDK, which isn't going to work in any case because tip of tree uses newer Vulkan-Headersversions.

If you were to download the corresponding Vulkan-Headers and provide that to Vulkan-Tools, then it should work as expected. (This is essentially all that update_deps.py does, clones Vulkan-Headers and makes it available to Vulkan-Tools).

**Comment by BlingRob** [comment]
You are absolutely right. My Vulkan-Headers was version 1.2.337 and Vulkan-Tools was incompatible with it. I studied the `update_deps.py`, `known_good.json` and found a suitable commit.
Thank you so much.
