### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-Tools#739]
Would you like to add more error handling for return values from functions like the following?
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [get_args](https://github.com/KhronosGroup/Vulkan-Tools/blob/80e16af0fd8f1f03374e4cc4eea4822520967e08/common/android_util.cpp#L70)
* [printf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output") ⇒ [dumpMatrix](https://github.com/KhronosGroup/Vulkan-Tools/blob/3d015f42a4ec56f20fbf1ccc3f55c36dc04fea40/cube/cube.c#L276)

**Comment by charles-lunarg** [comment]
Can you elaborate more on what you mean?

Both printf and malloc failing are... rare and not something that are commonly checked. I'm happy to take PR's which follow the code's existing error handling strategy which accounts for those functions. But malloc failing is almost non existent on desktop and printf failing is similar, so I do not consider it a priority.

**Comment by elfring** [comment]
:thought_balloon: I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by charles-lunarg** [comment]
Did you find an actual issue that earlier reporting would have helped? Unless there is an explicit example of checking the return value of malloc or printf *solving* a problem, I am unable to prioritize this for other things.

Malloc is also very very very unlikely to return an error code due to the virtual memory nature of modern computing. Out of memory conditions are only detectable when the OS tries to write memory to an address, not when it is allocated.

**Comment by elfring** [comment]
:thinking: [Can you adhere to secure programming guidelines](https://wiki.sei.cmu.edu/confluence/display/c/EXP12-C.+Do+not+ignore+values+returned+by+functions "Do not ignore values returned by functions") (so that [undefined software behaviour will be excluded](https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers "EXP34-C: Do not dereference null pointers"))?
