### ISSUE TITLE
vulkaninfo: not showing flags from VkFormatFeatureFlags2 

### ISSUE THREAD

**Issue by AlexRouSg** [KhronosGroup/Vulkan-Tools#751]
So I noticed that the flags from VkFormatFeatureFlags2 are not getting printed, would be nice to have that supported

**Comment by charles-lunarg** [comment]
Yep, this is a missing bit of functionality. Not terribly hard to add all-in-all, but does pose a challenge is how to display the info.

There are a couple of options I see.
1. Display everything separately. Print out the supported VkFormatFeatureFlags then print out the supported VkFormatFeatureFlags2 as a separate group. The bad part of this is effectively printing VkFormatFeatureFlags twice, since VkFormatFeatureFlags2 is a superset.

2. Display only VkFormatFeatureFlags2 if supported. The bad part here is only showing the VkFormatFeatureFlags2 version of everything.

3. Display VkFormatFeatureFlags as normal and append the VkFormatFeatureFlags2 at the end. This will take a bit more work to combine the two kinds of features and make sure none of the VkFormatFeatureFlags appear twice. But I think this is the best way to display the info. 

Still, I'd appreciate if you had an opinion on which of the 3 you'd prefer, or if there is a different way to do it that I haven't described here.

Note that the html & json outputs will likely use option 1 since they prefer to have everything (and most json viewers allow collapsing objects!) So this is primarily a text output question.

**Comment by AlexRouSg** [comment]
1 is definitely not ideal, however I don't feel strongly for 2 and 3.
Thought of having an arg to select between showing `VkFormatFeatureFlags`, `VkFormatFeatureFlags2`and maybe the option 3 hybrid but not sure if that improves it much.

If we think very long term, do we really want one new arg every time the spec adds a `Vk*FeatureFlagsN`?
Maybe if it's a set of global args like `--show-legacy-flags`, hmmmm

**Comment by charles-lunarg** [comment]
Thinking about it, 2 (VkFormatFeatureFlags2 by default) with just a fallback to VkFormatFeatureFlags if the newer isn't supported is both the cleanest and sanest way to do this.

It means users always get the most information that is available. If people want a 'show only `VkFormatFeatureFlags` option, they can ask for it.

**Comment by AlexRouSg** [comment]
SGTM, I don't have further comments
