### ISSUE TITLE
vkcube --validate crashing on Ubuntu packages only?

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-Tools#771]
https://discord.com/channels/427551838099996672/427951526967902218/1096185727307485214

```
VIA_INFO:    SDK Found! - Will attempt to run tests
VIA_INFO:       Attempting to run vkcube in 
VIA_INFO:           Command-line: vkcube --c 100 --suppress_popups
/usr/bin/vkcube
Selected GPU 0: Intel(R) UHD Graphics 620 (KBL GT2), type: IntegratedGpu
VIA_INFO:           Command-line: vkcube --c 100 --suppress_popups --validate
/usr/bin/vkcube
vkcube: symbol lookup error: /lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so: undefined symbol: _Z14get_chaininfoPK20VkInstanceCreateInfo16VkLayerFunction
VIA_ERROR:   Unknown Test failure occurred.
```

@charles-lunarg and I were helping a user on discord.

Essentially `vkcube --validate` was crashing for them.

I ended up suggesting using the tarball. Which ended up fixing the issue for the user.

I wasn't able to reproduce the issue locally, so I'm not 100% sure of the root cause.

**Comment by juan-lunarg** [comment]
@johnzupin is there anything in particular that would cause this kind of difference between the tarball/ubuntu package?

**Comment by charles-lunarg** [comment]
This appears to be the result of using Ubuntu packages that are patently incorrect. In this specific case, it is likely due to using a package which builds the validation layers from tip of tree (to make it available for older ubuntu releases) but using a patch that triggers this linking error.

In other cases, such as Ubuntu-latest & Fedora 38, it was due to the same underlying issue, patching the validation layer build to use SHARED instead of STATIC for the vk layer utils.

I am going to close the issue since this isn't something relevant to this repo. Also the Ubuntu-latest has fixed the issue, so that helps.
