### ISSUE TITLE
vulkaninfo not printing format properties for certain extension formats

### ISSUE THREAD

**Issue by jfitzpatrick-img** [KhronosGroup/Vulkan-Tools#916]
We are seeing issues when using vulkaninfo where some format properties are not being output in either the txt or json output.

It appears that the `supported_format_ranges` list in vulkaninfo.hpp (https://github.com/KhronosGroup/Vulkan-Tools/blob/main/vulkaninfo/vulkaninfo.h#L1877) is missing some of the format ranges from extensions in the spec

From a quick look, I can see the following ranges are missing (This list might not be complete):

- VK_EXT_4444_formats (`VK_FORMAT_A4R4G4B4_UNORM_PACK16` -> `VK_FORMAT_A4B4G4R4_UNORM_PACK16`)
- VK_KHR_maintenance5 (`VK_FORMAT_A1B5G5R5_UNORM_PACK16_KHR` -> `VK_FORMAT_A8_UNORM_KHR`)
- VK_NV_optical_flow (`VK_FORMAT_R16G16_S10_5_NV` -> `VK_FORMAT_R16G16_S10_5_NV`)
- VK_EXT_ycbcr_2plane_444_formats (`VK_FORMAT_G8_B8R8_2PLANE_444_UNORM` -> `VK_FORMAT_G16_B16R16_2PLANE_444_UNORM`)

**Comment by charles-lunarg** [comment]
Yep, this has been something that should have been fixed in 2019 when I rewrote vulkaninfo to use autogen, but the *difficulty* of it stopped me from trying. But since then, several extensions containing formats have been added without any updates here.

I'm working on a fix for it as we speak, and the difficulty isn't as high as I thought ( but some of that is because I'm much more adept at using the vk.xml these days)
