### ISSUE TITLE
Bug in 'linmath.h' function: quat_mul_vec3

### ISSUE THREAD

**Issue by dwolowb** [KhronosGroup/Vulkan-Tools#961]
The function quat_mul_vec3 is not used in the vkcube program, however it is included as part of linmath in the Vulkan-Tools repository. The expectation of the function is to rotate a vector by a quaternion. The bug is apparent when we take the identity quaternion and multiply a vector, we do not end up with that same vector. A correct implementation of this function is included below:
```
void quat_mul_vec3(vec3 r, quat q, vec3 v)
{
/*
 * Method by Fabian 'ryg' Giessen (of Farbrausch)
t = 2 * cross(q.xyz, v)
v' = v + q.w * t + cross(q.xyz, t)
 */
	vec3 t;
	vec3 q_xyz = {q[0], q[1], q[2]};
	vec3 u = {q[0], q[1], q[2]};

	vec3_mul_cross(t, q_xyz, v);
	vec3_scale(t, t, 2);

	vec3_mul_cross(u, q_xyz, t);
	vec3_scale(t, t, q[3]);

	vec3_add(r, v, t);
	vec3_add(r, r, u);
}
```

**Comment by charles-lunarg** [comment]
I appreciate you reporting the bug since others may taken linmath.h and been bitten by it. That said, I'm not sure whether to simply remove unused functions in linmath.h, as manually verifying each function (especially ones vkcube doesn't use) is time intensive, or ask that you make a PR to update linmath.h to a newer version as the upstream source appears to be https://github.com/datenwolf/linmath.h (assuming the upstream version has fixed this bug).
